// import type { Metadata } from "next";
import "./globals.css";
import TopAppBar from "../components/TopAppBar";
import { Outlet } from "react-router-dom";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout() {
  return (
    <>
      <TopAppBar />
      <Outlet />
    </>
  );
}
