import { ImageObject } from "./common/ImageObject"
import { ThumbnailObject } from "./common/ThumbnailObject"
import { VideoObject } from "./common/VideoObject"

export type SearchResults = (VideoSearchResult | PlaylistSearchResult | ChannelSearchResult)[]

export type VideoSearchResult = {
  type: "video",
  title: string,
  videoId: string,
  author: string,
  authorId: string,
  authorUrl: string,
  videoThumbnails: ThumbnailObject[],
  description: string,
  descriptionHtml: string,
  viewCount: number,
  published: number,
  publishedText: string,
  lengthSeconds: number,
  liveNow: boolean,
  paid: boolean,
  premium: boolean
}

export type PlaylistSearchResult = {
  type: "playlist",
  title: string,
  playlistId: string,
  playlistThumbnail: string,
  author: string,
  authorId: string,
  authorUrl: string,
  authorVerified: boolean,

  videoCount: number,
  videos: Pick<VideoObject,
    'title'
    | 'videoId'
    | 'lengthSeconds'
    | 'videoThumbnails'
  >[],
}

export type ChannelSearchResult = {
  type: "channel",
  author: string,
  authorId: string,
  authorUrl: string,

  authorThumbnails: ImageObject[],
  autoGenerated: boolean,
  subCount: number,
  videoCount: number,
  description: string,
  descriptionHtml: string
}